
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.ScratchCard
{
/// <summary>
/// 刮刮卡奖励
/// </summary>

public sealed partial class PrizeItem : Luban.BeanBase
{
    public PrizeItem(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Cash = (float)_obj.GetValue("cash");
        Num = (int)_obj.GetValue("num");
    }

    public static PrizeItem DeserializePrizeItem(JToken _buf)
    {
        return new ScratchCard.PrizeItem(_buf);
    }

    /// <summary>
    /// 奖励金额
    /// </summary>
    public readonly float Cash;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Num;


    public const int __ID__ = 472233537;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "cash:" + Cash + ","
        + "num:" + Num + ","
        + "}";
    }
}
}

