
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Type1 : Luban.BeanBase
{
    public Type1(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        A = (int)_obj.GetValue("a");
        B = (string)_obj.GetValue("b");
        C = (bool)_obj.GetValue("c");
    }

    public static Type1 DeserializeType1(JToken _buf)
    {
        return new Type1(_buf);
    }

    public readonly int A;
    public readonly string B;
    public readonly bool C;


    public const int __ID__ = 81291287;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "a:" + A + ","
        + "b:" + B + ","
        + "c:" + C + ","
        + "}";
    }
}
}

