
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
public partial class Tables
{
    public ScratchCard.TbScratchCardReward TbScratchCardReward {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbScratchCardReward = new ScratchCard.TbScratchCardReward(loader("scratchcard_tbscratchcardreward"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbScratchCardReward.ResolveRef(this);
    }
}

}

