
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg.ScratchCard
{

public sealed partial class ScratchCardReward : Luban.BeanBase
{
    public ScratchCardReward(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        { var __json0 = _obj.GetValue("prizeItems"); PrizeItems = new System.Collections.Generic.List<ScratchCard.PrizeItem>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { ScratchCard.PrizeItem __v0;  __v0 = ScratchCard.PrizeItem.DeserializePrizeItem(__e0);  PrizeItems.Add(__v0); }   }
        { var __json0 = _obj.GetValue("prizes"); Prizes = new System.Collections.Generic.List<ScratchCard.Prize>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { ScratchCard.Prize __v0;  __v0 = ScratchCard.Prize.DeserializePrize(__e0);  Prizes.Add(__v0); }   }
        { var __json0 = _obj.GetValue("extraPrizes"); ExtraPrizes = new System.Collections.Generic.List<ScratchCard.Prize>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { ScratchCard.Prize __v0;  __v0 = ScratchCard.Prize.DeserializePrize(__e0);  ExtraPrizes.Add(__v0); }   }
    }

    public static ScratchCardReward DeserializeScratchCardReward(JToken _buf)
    {
        return new ScratchCard.ScratchCardReward(_buf);
    }

    /// <summary>
    /// 注释行
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 0
    /// </summary>
    public readonly System.Collections.Generic.List<ScratchCard.PrizeItem> PrizeItems;
    /// <summary>
    /// }表示容器（ScratchCard.Prize的prizeItems字段）的数据读取结束
    /// </summary>
    public readonly System.Collections.Generic.List<ScratchCard.Prize> Prizes;
    public readonly System.Collections.Generic.List<ScratchCard.Prize> ExtraPrizes;


    public const int __ID__ = 669153525;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in PrizeItems) { _e?.ResolveRef(tables); }
        foreach (var _e in Prizes) { _e?.ResolveRef(tables); }
        foreach (var _e in ExtraPrizes) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "prizeItems:" + Luban.StringUtil.CollectionToString(PrizeItems) + ","
        + "prizes:" + Luban.StringUtil.CollectionToString(Prizes) + ","
        + "extraPrizes:" + Luban.StringUtil.CollectionToString(ExtraPrizes) + ","
        + "}";
    }
}
}

