
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.ScratchCard
{

public partial class TbScratchCardReward
{
    private readonly System.Collections.Generic.Dictionary<int, ScratchCard.ScratchCardReward> _dataMap;
    private readonly System.Collections.Generic.List<ScratchCard.ScratchCardReward> _dataList;
    
    public TbScratchCardReward(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ScratchCard.ScratchCardReward>();
        _dataList = new System.Collections.Generic.List<ScratchCard.ScratchCardReward>();
        
        foreach(JObject _ele in _buf)
        {
            ScratchCard.ScratchCardReward _v;
            _v = ScratchCard.ScratchCardReward.DeserializeScratchCardReward(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, ScratchCard.ScratchCardReward> DataMap => _dataMap;
    public System.Collections.Generic.List<ScratchCard.ScratchCardReward> DataList => _dataList;

    public ScratchCard.ScratchCardReward GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ScratchCard.ScratchCardReward Get(int key) => _dataMap[key];
    public ScratchCard.ScratchCardReward this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

