// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: example1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoTest {

  /// <summary>Holder for reflection information generated from example1.proto</summary>
  public static partial class Example1Reflection {

    #region Descriptor
    /// <summary>File descriptor for example1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Example1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5leGFtcGxlMS5wcm90bxIJUHJvdG9UZXN0Gg1leGFtcGxlLnByb3RvIo0E",
            "CgtUZXN0TWVzc2FnZRInCgdyZXF1ZXN0GAIgASgLMhYuUHJvdG9UZXN0LlRl",
            "c3RSZXF1ZXN0EikKCHJlc3BvbnNlGAYgASgLMhcuUHJvdG9UZXN0LlRlc3RS",
            "ZXNwb25zZRqvAgoMVGVzdE1lc3NhZ2UxEicKB3JlcXVlc3QYASABKAsyFi5Q",
            "cm90b1Rlc3QuVGVzdFJlcXVlc3QSKQoIcmVzcG9uc2UYAyABKAsyFy5Qcm90",
            "b1Rlc3QuVGVzdFJlc3BvbnNlGqMBCgxUZXN0TWVzc2FnZTMSJwoHcmVxdWVz",
            "dBgBIAEoCzIWLlByb3RvVGVzdC5UZXN0UmVxdWVzdBIpCghyZXNwb25zZRgC",
            "IAEoCzIXLlByb3RvVGVzdC5UZXN0UmVzcG9uc2USPwoIdGVzdEVudW0YAyAB",
            "KA4yLS5Qcm90b1Rlc3QuVGVzdE1lc3NhZ2UuVGVzdE1lc3NhZ2UxLlRlc3RF",
            "bnVtMSIfCglUZXN0RW51bTESCQoFQkVHSU4QABIHCgNFTkQQAUoECAIQAxpi",
            "CgxUZXN0TWVzc2FnZTISJwoHcmVxdWVzdBgBIAEoCzIWLlByb3RvVGVzdC5U",
            "ZXN0UmVxdWVzdBIpCghyZXNwb25zZRgCIAEoCzIXLlByb3RvVGVzdC5UZXN0",
            "UmVzcG9uc2VKBAgBEAJKBAgDEAZSCHRlc3RFbnVtYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ProtoTest.ExampleReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoTest.TestMessage), global::ProtoTest.TestMessage.Parser, new[]{ "Request", "Response" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ProtoTest.TestMessage.Types.TestMessage1), global::ProtoTest.TestMessage.Types.TestMessage1.Parser, new[]{ "Request", "Response" }, null, new[]{ typeof(global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestMessage3), global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestMessage3.Parser, new[]{ "Request", "Response", "TestEnum" }, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoTest.TestMessage.Types.TestMessage2), global::ProtoTest.TestMessage.Types.TestMessage2.Parser, new[]{ "Request", "Response" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 可嵌套
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TestMessage : pb::IMessage<TestMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestMessage> _parser = new pb::MessageParser<TestMessage>(() => new TestMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoTest.Example1Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMessage(TestMessage other) : this() {
      request_ = other.request_ != null ? other.request_.Clone() : null;
      response_ = other.response_ != null ? other.response_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMessage Clone() {
      return new TestMessage(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 2;
    private global::ProtoTest.TestRequest request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoTest.TestRequest Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 6;
    private global::ProtoTest.TestResponse response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoTest.TestResponse Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Request, other.Request)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (request_ != null) hash ^= Request.GetHashCode();
      if (response_ != null) hash ^= Response.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (request_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Request);
      }
      if (response_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (request_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Request);
      }
      if (response_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (request_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestMessage other) {
      if (other == null) {
        return;
      }
      if (other.request_ != null) {
        if (request_ == null) {
          Request = new global::ProtoTest.TestRequest();
        }
        Request.MergeFrom(other.Request);
      }
      if (other.response_ != null) {
        if (response_ == null) {
          Response = new global::ProtoTest.TestResponse();
        }
        Response.MergeFrom(other.Response);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (request_ == null) {
              Request = new global::ProtoTest.TestRequest();
            }
            input.ReadMessage(Request);
            break;
          }
          case 50: {
            if (response_ == null) {
              Response = new global::ProtoTest.TestResponse();
            }
            input.ReadMessage(Response);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            if (request_ == null) {
              Request = new global::ProtoTest.TestRequest();
            }
            input.ReadMessage(Request);
            break;
          }
          case 50: {
            if (response_ == null) {
              Response = new global::ProtoTest.TestResponse();
            }
            input.ReadMessage(Response);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the TestMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Level 1
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class TestMessage1 : pb::IMessage<TestMessage1>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<TestMessage1> _parser = new pb::MessageParser<TestMessage1>(() => new TestMessage1());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<TestMessage1> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ProtoTest.TestMessage.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TestMessage1() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TestMessage1(TestMessage1 other) : this() {
          request_ = other.request_ != null ? other.request_.Clone() : null;
          response_ = other.response_ != null ? other.response_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TestMessage1 Clone() {
          return new TestMessage1(this);
        }

        /// <summary>Field number for the "request" field.</summary>
        public const int RequestFieldNumber = 1;
        private global::ProtoTest.TestRequest request_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::ProtoTest.TestRequest Request {
          get { return request_; }
          set {
            request_ = value;
          }
        }

        /// <summary>Field number for the "response" field.</summary>
        public const int ResponseFieldNumber = 3;
        private global::ProtoTest.TestResponse response_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::ProtoTest.TestResponse Response {
          get { return response_; }
          set {
            response_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as TestMessage1);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(TestMessage1 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Request, other.Request)) return false;
          if (!object.Equals(Response, other.Response)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (request_ != null) hash ^= Request.GetHashCode();
          if (response_ != null) hash ^= Response.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (request_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Request);
          }
          if (response_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Response);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (request_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Request);
          }
          if (response_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Response);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (request_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
          }
          if (response_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(TestMessage1 other) {
          if (other == null) {
            return;
          }
          if (other.request_ != null) {
            if (request_ == null) {
              Request = new global::ProtoTest.TestRequest();
            }
            Request.MergeFrom(other.Request);
          }
          if (other.response_ != null) {
            if (response_ == null) {
              Response = new global::ProtoTest.TestResponse();
            }
            Response.MergeFrom(other.Response);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (request_ == null) {
                  Request = new global::ProtoTest.TestRequest();
                }
                input.ReadMessage(Request);
                break;
              }
              case 26: {
                if (response_ == null) {
                  Response = new global::ProtoTest.TestResponse();
                }
                input.ReadMessage(Response);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (request_ == null) {
                  Request = new global::ProtoTest.TestRequest();
                }
                input.ReadMessage(Request);
                break;
              }
              case 26: {
                if (response_ == null) {
                  Response = new global::ProtoTest.TestResponse();
                }
                input.ReadMessage(Response);
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the TestMessage1 message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          public enum TestEnum1 {
            [pbr::OriginalName("BEGIN")] Begin = 0,
            [pbr::OriginalName("END")] End = 1,
          }

          /// <summary>
          /// Level 2
          /// </summary>
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class TestMessage3 : pb::IMessage<TestMessage3>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<TestMessage3> _parser = new pb::MessageParser<TestMessage3>(() => new TestMessage3());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<TestMessage3> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::ProtoTest.TestMessage.Types.TestMessage1.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public TestMessage3() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public TestMessage3(TestMessage3 other) : this() {
              request_ = other.request_ != null ? other.request_.Clone() : null;
              response_ = other.response_ != null ? other.response_.Clone() : null;
              testEnum_ = other.testEnum_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public TestMessage3 Clone() {
              return new TestMessage3(this);
            }

            /// <summary>Field number for the "request" field.</summary>
            public const int RequestFieldNumber = 1;
            private global::ProtoTest.TestRequest request_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::ProtoTest.TestRequest Request {
              get { return request_; }
              set {
                request_ = value;
              }
            }

            /// <summary>Field number for the "response" field.</summary>
            public const int ResponseFieldNumber = 2;
            private global::ProtoTest.TestResponse response_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::ProtoTest.TestResponse Response {
              get { return response_; }
              set {
                response_ = value;
              }
            }

            /// <summary>Field number for the "testEnum" field.</summary>
            public const int TestEnumFieldNumber = 3;
            private global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1 testEnum_ = global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1.Begin;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1 TestEnum {
              get { return testEnum_; }
              set {
                testEnum_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as TestMessage3);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(TestMessage3 other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (!object.Equals(Request, other.Request)) return false;
              if (!object.Equals(Response, other.Response)) return false;
              if (TestEnum != other.TestEnum) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (request_ != null) hash ^= Request.GetHashCode();
              if (response_ != null) hash ^= Response.GetHashCode();
              if (TestEnum != global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1.Begin) hash ^= TestEnum.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (request_ != null) {
                output.WriteRawTag(10);
                output.WriteMessage(Request);
              }
              if (response_ != null) {
                output.WriteRawTag(18);
                output.WriteMessage(Response);
              }
              if (TestEnum != global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1.Begin) {
                output.WriteRawTag(24);
                output.WriteEnum((int) TestEnum);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (request_ != null) {
                output.WriteRawTag(10);
                output.WriteMessage(Request);
              }
              if (response_ != null) {
                output.WriteRawTag(18);
                output.WriteMessage(Response);
              }
              if (TestEnum != global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1.Begin) {
                output.WriteRawTag(24);
                output.WriteEnum((int) TestEnum);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (request_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
              }
              if (response_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
              }
              if (TestEnum != global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1.Begin) {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TestEnum);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(TestMessage3 other) {
              if (other == null) {
                return;
              }
              if (other.request_ != null) {
                if (request_ == null) {
                  Request = new global::ProtoTest.TestRequest();
                }
                Request.MergeFrom(other.Request);
              }
              if (other.response_ != null) {
                if (response_ == null) {
                  Response = new global::ProtoTest.TestResponse();
                }
                Response.MergeFrom(other.Response);
              }
              if (other.TestEnum != global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1.Begin) {
                TestEnum = other.TestEnum;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    if (request_ == null) {
                      Request = new global::ProtoTest.TestRequest();
                    }
                    input.ReadMessage(Request);
                    break;
                  }
                  case 18: {
                    if (response_ == null) {
                      Response = new global::ProtoTest.TestResponse();
                    }
                    input.ReadMessage(Response);
                    break;
                  }
                  case 24: {
                    TestEnum = (global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1) input.ReadEnum();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 10: {
                    if (request_ == null) {
                      Request = new global::ProtoTest.TestRequest();
                    }
                    input.ReadMessage(Request);
                    break;
                  }
                  case 18: {
                    if (response_ == null) {
                      Response = new global::ProtoTest.TestResponse();
                    }
                    input.ReadMessage(Response);
                    break;
                  }
                  case 24: {
                    TestEnum = (global::ProtoTest.TestMessage.Types.TestMessage1.Types.TestEnum1) input.ReadEnum();
                    break;
                  }
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

      /// <summary>
      /// Level 1
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class TestMessage2 : pb::IMessage<TestMessage2>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<TestMessage2> _parser = new pb::MessageParser<TestMessage2>(() => new TestMessage2());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<TestMessage2> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ProtoTest.TestMessage.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TestMessage2() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TestMessage2(TestMessage2 other) : this() {
          request_ = other.request_ != null ? other.request_.Clone() : null;
          response_ = other.response_ != null ? other.response_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TestMessage2 Clone() {
          return new TestMessage2(this);
        }

        /// <summary>Field number for the "request" field.</summary>
        public const int RequestFieldNumber = 1;
        private global::ProtoTest.TestRequest request_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::ProtoTest.TestRequest Request {
          get { return request_; }
          set {
            request_ = value;
          }
        }

        /// <summary>Field number for the "response" field.</summary>
        public const int ResponseFieldNumber = 2;
        private global::ProtoTest.TestResponse response_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::ProtoTest.TestResponse Response {
          get { return response_; }
          set {
            response_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as TestMessage2);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(TestMessage2 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Request, other.Request)) return false;
          if (!object.Equals(Response, other.Response)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (request_ != null) hash ^= Request.GetHashCode();
          if (response_ != null) hash ^= Response.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (request_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Request);
          }
          if (response_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Response);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (request_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Request);
          }
          if (response_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Response);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (request_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
          }
          if (response_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(TestMessage2 other) {
          if (other == null) {
            return;
          }
          if (other.request_ != null) {
            if (request_ == null) {
              Request = new global::ProtoTest.TestRequest();
            }
            Request.MergeFrom(other.Request);
          }
          if (other.response_ != null) {
            if (response_ == null) {
              Response = new global::ProtoTest.TestResponse();
            }
            Response.MergeFrom(other.Response);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (request_ == null) {
                  Request = new global::ProtoTest.TestRequest();
                }
                input.ReadMessage(Request);
                break;
              }
              case 18: {
                if (response_ == null) {
                  Response = new global::ProtoTest.TestResponse();
                }
                input.ReadMessage(Response);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (request_ == null) {
                  Request = new global::ProtoTest.TestRequest();
                }
                input.ReadMessage(Request);
                break;
              }
              case 18: {
                if (response_ == null) {
                  Response = new global::ProtoTest.TestResponse();
                }
                input.ReadMessage(Response);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
