
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Type4 : Luban.BeanBase
{
    public Type4(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        A = (string)_obj.GetValue("a");
        C = Vec3.DeserializeVec3(_obj.GetValue("c"));
    }

    public static Type4 DeserializeType4(JToken _buf)
    {
        return new Type4(_buf);
    }

    public readonly string A;
    public readonly Vec3 C;


    public const int __ID__ = 81291290;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        C?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "a:" + A + ","
        + "c:" + C + ","
        + "}";
    }
}
}

