
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Title1 : Luban.BeanBase
{
    public Title1(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        A = (int)_obj.GetValue("a");
        B = (string)_obj.GetValue("b");
        C = Title2.DeserializeTitle2(_obj.GetValue("c"));
    }

    public static Title1 DeserializeTitle1(JToken _buf)
    {
        return new Title1(_buf);
    }

    public readonly int A;
    public readonly string B;
    public readonly Title2 C;


    public const int __ID__ = -1789586183;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        C?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "a:" + A + ","
        + "b:" + B + ","
        + "c:" + C + ","
        + "}";
    }
}
}

