
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Type2 : Luban.BeanBase
{
    public Type2(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        A = (int)_obj.GetValue("a");
        B = (bool)_obj.GetValue("b");
        C = Type1.DeserializeType1(_obj.GetValue("c"));
    }

    public static Type2 DeserializeType2(JToken _buf)
    {
        return new Type2(_buf);
    }

    public readonly int A;
    public readonly bool B;
    public readonly Type1 C;


    public const int __ID__ = 81291288;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        C?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "a:" + A + ","
        + "b:" + B + ","
        + "c:" + C + ","
        + "}";
    }
}
}

