
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Vec3 : Luban.BeanBase
{
    public Vec3(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        X = (float)_obj.GetValue("x");
        Y = (float)_obj.GetValue("y");
        Z = (float)_obj.GetValue("z");
    }

    public static Vec3 DeserializeVec3(JToken _buf)
    {
        return new Vec3(_buf);
    }

    public readonly float X;
    public readonly float Y;
    public readonly float Z;


    public const int __ID__ = 2662207;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "z:" + Z + ","
        + "}";
    }
}
}

